pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                dir('jenkins-docker-demo') {
                    sh 'docker build -t jenkins-demo:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Scan Image') {
            steps {
                sh 'trivy image --exit-code 1 --severity HIGH,CRITICAL jenkins-demo:${BUILD_NUMBER}'
            }
        }
    }
}
